@BlazorInvoice.KositApiWrapper_HostAddress = http://localhost:5025

POST {{BlazorInvoice.KositApiWrapper_HostAddress}}/validate/
Accept: application/xml

<?xml version="1.0"?>
<Invoice>
  <ID>123</ID>
  <Date>2024-01-01</Date>
</Invoice>
###
