//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorInvoice.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InvoiceLoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvoiceLoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorInvoice.Localization.InvoiceLoc", typeof(InvoiceLoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique identifier of the invoice that identifies it in the seller&apos;s system..
        /// </summary>
        public static string BT_1 {
            get {
                return ResourceManager.GetString("BT-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An identifier assigned by the buyer and used for internal management purposes..
        /// </summary>
        public static string BT_10 {
            get {
                return ResourceManager.GetString("BT-10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code for the VAT category applicable to the invoiced item..
        /// </summary>
        public static string BT_118 {
            get {
                return ResourceManager.GetString("BT-118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The percentage of VAT applicable to the invoiced item..
        /// </summary>
        public static string BT_119 {
            get {
                return ResourceManager.GetString("BT-119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A text note containing unstructured information relevant to the invoice line item..
        /// </summary>
        public static string BT_127 {
            get {
                return ResourceManager.GetString("BT-127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An identifier provided by the seller for an item to which the invoice line refers..
        /// </summary>
        public static string BT_128 {
            get {
                return ResourceManager.GetString("BT-128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity of the individual items (goods or services) invoiced in the respective line..
        /// </summary>
        public static string BT_129 {
            get {
                return ResourceManager.GetString("BT-129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total amount of the invoice line. This is the amount excluding VAT but including all discounts, charges, and other applicable taxes related to the invoice line..
        /// </summary>
        public static string BT_131 {
            get {
                return ResourceManager.GetString("BT-131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A text value indicating where the relevant data should be recorded in the buyer&apos;s financial accounts..
        /// </summary>
        public static string BT_133 {
            get {
                return ResourceManager.GetString("BT-133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price of an item, excluding VAT, after the discount applicable to this invoice line has been deducted..
        /// </summary>
        public static string BT_146 {
            get {
                return ResourceManager.GetString("BT-146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total discount subtracted from the gross item price to calculate the net item price..
        /// </summary>
        public static string BT_147 {
            get {
                return ResourceManager.GetString("BT-147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of units for which the item price applies..
        /// </summary>
        public static string BT_149 {
            get {
                return ResourceManager.GetString("BT-149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the item. (Required).
        /// </summary>
        public static string BT_153 {
            get {
                return ResourceManager.GetString("BT-153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the item. (Optional).
        /// </summary>
        public static string BT_154 {
            get {
                return ResourceManager.GetString("BT-154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller&apos;s identifier for the item. (Optional).
        /// </summary>
        public static string BT_155 {
            get {
                return ResourceManager.GetString("BT-155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer&apos;s identifier for the item. (Optional).
        /// </summary>
        public static string BT_156 {
            get {
                return ResourceManager.GetString("BT-156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard identifier for the item. (Optional).
        /// </summary>
        public static string BT_157 {
            get {
                return ResourceManager.GetString("BT-157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the item&apos;s property, such as &quot;Color.&quot;.
        /// </summary>
        public static string BT_160 {
            get {
                return ResourceManager.GetString("BT-160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the item&apos;s property, such as &quot;red.&quot;.
        /// </summary>
        public static string BT_161 {
            get {
                return ResourceManager.GetString("BT-161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date the invoice was issued..
        /// </summary>
        public static string BT_2 {
            get {
                return ResourceManager.GetString("BT-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full name under which the seller is registered in the national register for legal entities or as a taxable person, or otherwise operates as a business entity (company name)..
        /// </summary>
        public static string BT_27 {
            get {
                return ResourceManager.GetString("BT-27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A code indicating the functional type of the invoice..
        /// </summary>
        public static string BT_3 {
            get {
                return ResourceManager.GetString("BT-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main line in an address. This is typically either the street name and house number or the text &quot;P.O. Box&quot; followed by the P.O. Box number..
        /// </summary>
        public static string BT_35 {
            get {
                return ResourceManager.GetString("BT-35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the city or municipality where the seller&apos;s address is located..
        /// </summary>
        public static string BT_37 {
            get {
                return ResourceManager.GetString("BT-37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The postal code..
        /// </summary>
        public static string BT_38 {
            get {
                return ResourceManager.GetString("BT-38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A code used to designate the country..
        /// </summary>
        public static string BT_40 {
            get {
                return ResourceManager.GetString("BT-40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of a contact person or contact point (such as the name of a person, department, or office designation)..
        /// </summary>
        public static string BT_41 {
            get {
                return ResourceManager.GetString("BT-41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone number of the contact person or contact point..
        /// </summary>
        public static string BT_42 {
            get {
                return ResourceManager.GetString("BT-42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email address of the contact person or contact point..
        /// </summary>
        public static string BT_43 {
            get {
                return ResourceManager.GetString("BT-43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currency in which all invoice amounts are specified, except for the total VAT amount, which must be stated in the settlement currency..
        /// </summary>
        public static string BT_5 {
            get {
                return ResourceManager.GetString("BT-5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The due date of the invoice amount..
        /// </summary>
        public static string BT_9 {
            get {
                return ResourceManager.GetString("BT-9", resourceCulture);
            }
        }
    }
}
